# Decision Tree Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

## Importing the dataset

In [3]:
dataset = pd.read_csv(r"C:\Users\Lenovo\Downloads\Rehackt_FloodPrediction-main\backend\Code_Notebook\FloodPred.csv")
mon = {"JANUARY":1, "FEBRUARY":2, "MARCH":3, "APRIL":4, "MAY":5, "JUNE":6, "JULY":7, "AUGUST":8, "SEPTEMBER":9, "OCTOBER":10, "NOVEMBER":11, "DECEMBER":12}
dataset['MONTH'] = dataset['MONTH'].map(mon)

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(dataset)


              LOCATION  YEAR  MONTH  MIN_TEMP  MAX_TEMP  RAINFALL  \
0          BIHAR-PATNA  1992      1     8.067    22.456    20.727   
1          BIHAR-PATNA  1992      2     9.776    24.752     5.904   
2          BIHAR-PATNA  1992      3    17.734    34.124     1.126   
3          BIHAR-PATNA  1992      4    22.842    38.889     4.345   
4          BIHAR-PATNA  1992      5    24.716    39.157     8.737   
...                ...   ...    ...       ...       ...       ...   
2635  ORISSA-SAMBALPUR  2002      8    23.754    30.272   459.220   
2636  ORISSA-SAMBALPUR  2002      9    23.702    31.314   142.111   
2637  ORISSA-SAMBALPUR  2002     10    21.689    31.581    38.260   
2638  ORISSA-SAMBALPUR  2002     11    16.794    29.344    11.144   
2639  ORISSA-SAMBALPUR  2002     12    14.072    28.093     0.000   

      CLOUD_COVER  WET_DAY_FREQ  DIURNAL_TEMP FLOOD OCCURRENCE  
0          22.672        1.5696        14.389               NO  
1          22.846        1.0000        14

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X=np.array(columnTransformer.fit_transform(X),dtype=np.str)
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)


## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(X_train)

[['0' '0.0' '0.0' ... '11.822000000000001' '1.0096' '14.012']
 ['0' '0.0' '0.0' ... '24.429000000000002' '0.9999' '13.306']
 ['0' '0.0' '0.0' ... '50.891999999999996' '5.2088' '11.549000000000001']
 ...
 ['0' '0.0' '0.0' ... '69.66199999999999' '11.8621' '6.606']
 ['0' '0.0' '0.0' ... '30.504' '4.6386' '8.506']
 ['0' '0.0' '0.0' ... '19.477999999999998' '1.8468' '14.634']]


In [7]:
print(y_train)

[0 0 0 ... 1 0 0]


In [8]:
print(X_test)

[['0' '0.0' '0.0' ... '76.327' '14.9156' '6.1610000000000005']
 ['0' '0.0' '0.0' ... '58.755' '7.6699' '6.642']
 ['0' '0.0' '0.0' ... '24.8' '0.9999' '15.784']
 ...
 ['0' '0.0' '0.0' ... '31.955' '1.4107' '14.817']
 ['0' '0.0' '1.0' ... '12.652000000000001' '0.0' '15.189']
 ['0' '0.0' '0.0' ... '23.169' '1.6587' '11.634']]


In [9]:
print(y_test)

[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [11]:
print(X_train)

[[-0.2306328  -0.22573306 -0.22325083 ... -1.48482014 -0.52498847
   1.04767606]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.8648489  -0.52568132
   0.83168825]
 [-0.2306328  -0.22573306 -0.22325083 ...  0.43651532 -0.22504724
   0.29416619]
 ...
 [-0.2306328  -0.22573306 -0.22325083 ...  1.35956284  0.25018589
  -1.21805439]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.56610017 -0.26577559
  -0.63678409]
 [-0.2306328  -0.22573306 -0.22325083 ... -1.10832297 -0.4651888
   1.2379656 ]]


In [12]:
print(X_test)

[[-0.2306328  -0.22573306 -0.22325083 ...  1.68732585  0.46829185
  -1.35419401]
 [-0.2306328  -0.22573306 -0.22325083 ...  0.82319208 -0.04925534
  -1.20704085]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.84660433 -0.52568132
   1.5897871 ]
 ...
 [-0.2306328  -0.22573306 -0.22325083 ... -0.49474471 -0.49633863
   1.29395111]
 [-0.2306328  -0.22573306  4.47926666 ... -1.44400344 -0.59710236
   1.40775772]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.9268116  -0.47862444
   0.32017039]]


## Training the Decision Tree Classification model on the Training set

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Predicting the Test set results

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[547  23]
 [ 14  76]]


0.943939393939394

In [16]:
filename= 'flood_pred_model'
pickle.dump(classifier,open(filename,'wb'))

In [17]:
loaded_model = pickle.load(open(filename,'rb'))
loaded_model.predict(X_test)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,