# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv(r"C:\Users\Lenovo\Downloads\Rehackt_FloodPrediction-main\backend\Code_Notebook\FloodPred.csv")
#mon = {"JANUARY":1, "FEBRUARY":2, "MARCH":3, "APRIL":4, "MAY":5, "JUNE":6, "JULY":7, "AUGUST":8, "SEPTEMBER":9, "OCTOBER":10, "NOVEMBER":11, "DECEMBER":12}
#dataset['MONTH'] = dataset['MONTH'].map(mon)

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(dataset)


      Rainfall SST  Wind Speed (km/h)         State  elevation        lat  \
0        65.24  45            14.1197        Kerala  54.553295  14.640394   
1       162.91  39            14.2646  AndraPradesh  21.856272  14.698299   
2       146.34  32             3.9284   Uttarakhand  69.322807  14.698858   
3        17.77  31            14.1036        Kerala  10.987241  14.571310   
4        41.90  41            11.0446   Uttarakhand  87.889847  14.762232   
...        ...  ..                ...           ...        ...        ...   
3495    172.19  63            16.0034        Kerala  48.399899  14.634114   
3496     46.53  70            15.4238   Uttarakhand  20.291956  14.626105   
3497    112.09  72            17.2431  AndraPradesh  12.405437  14.625527   
3498     10.16  62            17.4363        Kerala  17.630608  14.625669   
3499    110.80  63            16.8406  AndraPradesh  43.330071  14.709428   

             lon  
0     121.055708  
1     121.002132  
2     121.100261  

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='ignore')
X=np.array(columnTransformer.fit_transform(X),dtype=np.str)
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)


ValueError: The remainder keyword needs to be one of 'drop', 'passthrough', or estimator. 'ignore' was passed instead

## Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [16]:
print(X_train)

[['0' '1.0' 'SAMBALPUR' '1' '7.681']
 ['1' '0.0' 'SARAN' '11' '22.169']
 ['1' '0.0' 'KISHANGANJ' '5' '92.88799999999999']
 ...
 ['1' '0.0' 'WESTCHAMPARAN' '8' '345.07800000000003']
 ['0' '1.0' 'CUTTACK' '10' '78.164']
 ['0' '1.0' 'SAMBALPUR' '4' '21.439']]


In [17]:
print(y_train)

[0 0 0 ... 1 0 0]


In [18]:
print(X_test)

[['0' '1.0' 'BALESHWAR' '8' '365.664']
 ['0' '1.0' 'BALESHWAR' '9' '109.12700000000001']
 ['1' '0.0' 'WESTCHAMPARAN' '4' '6.855']
 ...
 ['1' '0.0' 'KISHANGANJ' '3' '15.273']
 ['1' '0.0' 'GOPALGANJ' '11' '0.0']
 ['0' '1.0' 'BALESHWAR' '1' '29.967']]


In [19]:
print(y_test)

[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

## Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

ValueError: could not convert string to float: 'WESTCHAMPARAN'

In [11]:
print(X_train)

[[-0.2306328  -0.22573306 -0.22325083 ... -1.48482014 -0.52498847
   1.04767606]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.8648489  -0.52568132
   0.83168825]
 [-0.2306328  -0.22573306 -0.22325083 ...  0.43651532 -0.22504724
   0.29416619]
 ...
 [-0.2306328  -0.22573306 -0.22325083 ...  1.35956284  0.25018589
  -1.21805439]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.56610017 -0.26577559
  -0.63678409]
 [-0.2306328  -0.22573306 -0.22325083 ... -1.10832297 -0.4651888
   1.2379656 ]]


In [12]:
print(X_test)

[[-0.2306328  -0.22573306 -0.22325083 ...  1.68732585  0.46829185
  -1.35419401]
 [-0.2306328  -0.22573306 -0.22325083 ...  0.82319208 -0.04925534
  -1.20704085]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.84660433 -0.52568132
   1.5897871 ]
 ...
 [-0.2306328  -0.22573306 -0.22325083 ... -0.49474471 -0.49633863
   1.29395111]
 [-0.2306328  -0.22573306  4.47926666 ... -1.44400344 -0.59710236
   1.40775772]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.9268116  -0.47862444
   0.32017039]]


## Training the Logistic Regression model on the Training set

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the Test set results

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[548  22]
 [ 43  47]]


0.9015151515151515