# Decision Tree Classification

## Importing the libraries

In [8]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


## Importing the dataset

In [3]:
dataset = pd.read_csv(r"C:\Users\Lenovo\Downloads\Rehackt_FloodPrediction-main\backend\Code_Notebook\FloodPred.csv")

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

print(dataset)


      Rainfall SST  Wind Speed (km/h)         State  elevation        lat  \
0        65.24  45            14.1197        Kerala  54.553295  14.640394   
1       162.91  39            14.2646  AndraPradesh  21.856272  14.698299   
2       146.34  32             3.9284   Uttarakhand  69.322807  14.698858   
3        17.77  31            14.1036        Kerala  10.987241  14.571310   
4        41.90  41            11.0446   Uttarakhand  87.889847  14.762232   
...        ...  ..                ...           ...        ...        ...   
3495    172.19  63            16.0034        Kerala  48.399899  14.634114   
3496     46.53  70            15.4238   Uttarakhand  20.291956  14.626105   
3497    112.09  72            17.2431  AndraPradesh  12.405437  14.625527   
3498     10.16  62            17.4363        Kerala  17.630608  14.625669   
3499    110.80  63            16.8406  AndraPradesh  43.330071  14.709428   

             lon  
0     121.055708  
1     121.002132  
2     121.100261  

In [25]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
#columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#X=np.array(columnTransformer.fit_transform(X),dtype=np.str)
#labelencoder_X = LabelEncoder()
#X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

#labelencoder_y = LabelEncoder()
#y = labelencoder_y.fit_transform(y)
onehotencoder = OneHotEncoder(handle_unknown='ignore')
transformed = onehotencoder.fit_transform(X[:, [4]]).toarray()




## Splitting the dataset into the Training set and Test set

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [27]:
print(X_train)

[[94.88 '54' 13.8138 'Uttarakhand' 3.35215807 14.71092916]
 [66.19 '77' 27.7242 'Uttarakhand' 24.90296745 14.72187906]
 [7.1 '42' 8.7745 'AndraPradesh' 4.2087345119999995 14.692834]
 ...
 [35.64 '33' 3.0268 'Kerala' 8.088683128 14.53983904]
 [35.64 '79' 17.9032 'Uttarakhand' 10.06401825 14.60729733]
 [54.63 '47' 4.8461 'AndraPradesh' 6.503358841 14.50142585]]


In [28]:
print(y_train)

[ 3.35215807 24.90296745  4.20873451 ...  8.08868313 10.06401825
  6.50335884]


In [29]:
print(X_test)

[[256.07 '75' 15.3111 'Kerala' 53.45264435 14.63977]
 [41.42 '59' 13.685 'Uttarakhand' 8.945150375 14.52881038]
 [65.24 '76' 13.8621 'AndraPradesh' 8.122948647000001 14.53486]
 ...
 [17.96 '57' 3.1073 'Uttarakhand' 5.383453846 14.7599111]
 [16.58 '61' 4.9588 'Uttarakhand' 7.41759491 14.55259942]
 [164.01 '46' 9.2253 'Uttarakhand' 9.61423111 14.46423456]]


In [30]:
print(y_test)

[53.45264435  8.94515038  8.12294865  6.98817587  7.55636692  5.58905506
  7.429461    5.17410612  5.98527813  8.79203701  9.38443184 18.17665291
  4.69410896 69.71452332  6.86212444 14.37593174 23.17574883 19.42672539
  6.09927893  6.48507404 61.06370544  8.90548515  4.97947407 12.20876503
 13.52340889 10.50982189  5.59923792 53.82743454  3.35215807 11.1982832
  8.57625484  6.37589216  7.34513187  4.95889425 55.05949402  3.10906577
  7.24331522  7.21340465  2.59821558  8.38349628 16.94276428  6.07521725
  5.88254404 12.08116436 22.66096306 43.50709152 13.3708601  10.08353901
 56.13411713  5.16008997 12.09593964  9.77402878  6.79264402 11.37576962
 13.34814167 33.51586914  6.44954014  9.72264862  9.38077641 15.57628536
 12.58471203 18.72412682  3.27494383 13.24690628  8.00370121 11.091609
  9.190629   11.54056168  2.4564085  41.61290741 10.81846523  8.86846829
  7.19411326  3.73873663  8.82925797 51.55602264 20.36778069 15.43967819
 18.94224358  8.16081715 14.61780548 11.18343353 12.46

## Feature Scaling

In [33]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


ValueError: could not convert string to float: 'Uttarakhand'

In [11]:
print(X_train)

[[-0.2306328  -0.22573306 -0.22325083 ... -1.48482014 -0.52498847
   1.04767606]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.8648489  -0.52568132
   0.83168825]
 [-0.2306328  -0.22573306 -0.22325083 ...  0.43651532 -0.22504724
   0.29416619]
 ...
 [-0.2306328  -0.22573306 -0.22325083 ...  1.35956284  0.25018589
  -1.21805439]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.56610017 -0.26577559
  -0.63678409]
 [-0.2306328  -0.22573306 -0.22325083 ... -1.10832297 -0.4651888
   1.2379656 ]]


In [12]:
print(X_test)

[[-0.2306328  -0.22573306 -0.22325083 ...  1.68732585  0.46829185
  -1.35419401]
 [-0.2306328  -0.22573306 -0.22325083 ...  0.82319208 -0.04925534
  -1.20704085]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.84660433 -0.52568132
   1.5897871 ]
 ...
 [-0.2306328  -0.22573306 -0.22325083 ... -0.49474471 -0.49633863
   1.29395111]
 [-0.2306328  -0.22573306  4.47926666 ... -1.44400344 -0.59710236
   1.40775772]
 [-0.2306328  -0.22573306 -0.22325083 ... -0.9268116  -0.47862444
   0.32017039]]


## Training the Decision Tree Classification model on the Training set

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Predicting the Test set results

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[547  23]
 [ 14  76]]


0.943939393939394

In [16]:
filename= 'flood_pred_model'
pickle.dump(classifier,open(filename,'wb'))

In [17]:
loaded_model = pickle.load(open(filename,'rb'))
loaded_model.predict(X_test)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,